In [1]:
# import module

import pandas as pd

In [2]:
df = pd.read_csv("reviews.csv")

print("Successfully created dataframe!")

Successfully created dataframe!

In [5]:
# get metadata
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 775 entries, 0 to 774
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Index           775 non-null    int64
 1   Name            775 non-null    str
 2   Overall_Rating  775 non-null    str
 3   Cuisine         775 non-null    str
 4   Rate for two    775 non-null    str
 5   City            775 non-null    str
 6   Review          775 non-null    str
dtypes: int64(1), str(6)
memory usage: 42.5 KB

In [3]:
# display first 5 and last 5 rows
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)


print("First 5 rows: ")
display(df.head())

print()
print("Last 5 rows: ")
display(df.tail())

First 5 rows:

,Index,Name,Overall_Rating,Cuisine,Rate for two,City,Review
0,0,Oliver Brown,3.9,"Cafe, Coffee, Shake, Juices, Beverages, Waffle...",500,ahmedabad,Been to this place 3-4 times. Prakash is alway...
1,1,Oliver Brown,3.9,"Cafe, Coffee, Shake, Juices, Beverages, Waffle...",500,ahmedabad,I recently visited Oliver Brown on a weekend f...
2,2,Crush Coffee,3,"Cafe, Shake, Beverages, Desserts",600,ahmedabad,Very watery ans thin shake
3,3,The Mohalla,3.8,Cafe,550,ahmedabad,it was not cheese burst pizza.. only cheeze wa...
4,4,The Mohalla,3.8,Cafe,550,ahmedabad,"Yammi.,....test burger is best I love 💗 this B..."

Last 5 rows:

,Index,Name,Overall_Rating,Cuisine,Rate for two,City,Review
770,770,The Food Garden,-,"Cafe, Salad, Healthy Food, Fast Food, North In...",850,chandigarh,The taste is good but the quantity is low as c...
771,771,The Food Garden,-,"Cafe, Salad, Healthy Food, Fast Food, North In...",850,chandigarh,pathetic food rejected
772,772,The Food Garden,-,"Cafe, Salad, Healthy Food, Fast Food, North In...",850,chandigarh,"thupka pack on cold drink packing, taste less,..."
773,773,The Food Garden,-,"Cafe, Salad, Healthy Food, Fast Food, North In...",850,chandigarh,very fast dilver
774,774,The Food Garden,-,"Cafe, Salad, Healthy Food, Fast Food, North In...",850,chandigarh,Tried their Hummus and Pita bread today. Didn'...

In [6]:
# check for missing
df.isnull().sum()

Index             0
Name              0
Overall_Rating    0
Cuisine           0
Rate for two      0
City              0
Review            0
dtype: int64

In [7]:
df.isna().any()

Index             False
Name              False
Overall_Rating    False
Cuisine           False
Rate for two      False
City              False
Review            False
dtype: bool

In [8]:
# check duplicates
df.duplicated().sum()

np.int64(0)

In [9]:
df[df.duplicated()]

Empty DataFrame
Columns: [Index, Name, Overall_Rating, Cuisine, Rate for two, City, Review]
Index: []

In [10]:
# check if review has empty strings
df['Review'].isna().sum()

np.int64(0)

In [12]:
# check review column duplicates
df['Review'].duplicated().sum()

np.int64(4)

Duplicate review texts were identified. Most duplicates consist of generic short reviews such as "good" and occur across different restaurants, while one pair appears to be a duplicate record for the same restaurant. These records will be retained pending further validation.

In [13]:
# inspect dups
# check all occurances
df[df['Review'].duplicated(keep=False)].sort_values('Review')

,Index,Name,Overall_Rating,Cuisine,Rate for two,City,Review
84,84,Shiva's Coffee Bar,-,"Cafe, Mexican, Pizza, South Indian, Chinese, F...",700,ahmedabad,good
93,93,Tony Cafe,-,"Cafe, Sandwich, Burger, Pizza, Fast Food, Chin...",700,ahmedabad,good
277,277,The Coffee House,4,"Cafe, North Indian, Fast Food, South Indian, S...",600,bangalore,good
598,598,Cafe Coffee Day,3,"Cafe, Coffee, Tea, Fast Food, Desserts, Bevera...",700,surat,good
405,405,Cosmo Bar & Bistro,4.1,"North Indian, Continental, Beverages, Chinese,...",700,udaipur,nice food
408,408,Cosmo Bar & Bistro,4.1,"North Indian, Continental, Beverages, Chinese,...",700,udaipur,nice food

In [17]:
# check unique values for overall rating
df['Overall_Rating'].unique()

<StringArray>
['3.9',   '3', '3.8', '4.3', '3.7', '4.8', '4.1',   '4', '4.2', '3.6', '4.4',
   '-', '3.5', '3.4', '3.1', '3.3', '3.2', '4.5', '4.9', 'New', '2.8', '2.7',
 '2.5', '2.9', '2.6']
Length: 25, dtype: str

In [18]:
# count how many times each rating appears
df['Overall_Rating'].value_counts()

Overall_Rating
3.9    92
4      78
-      76
4.1    56
4.2    50
3.7    49
3.8    45
3.5    44
New    41
4.3    35
3.4    32
3.6    30
3.3    23
3      21
3.1    21
3.2    18
4.5    18
2.7    11
4.4     8
4.8     7
2.8     6
2.9     5
2.5     4
4.9     3
2.6     2
Name: count, dtype: int64

In [19]:
# to include missing values
df['Overall_Rating'].value_counts(dropna=False)

Overall_Rating
3.9    92
4      78
-      76
4.1    56
4.2    50
3.7    49
3.8    45
3.5    44
New    41
4.3    35
3.4    32
3.6    30
3.3    23
3      21
3.1    21
3.2    18
4.5    18
2.7    11
4.4     8
4.8     7
2.8     6
2.9     5
2.5     4
4.9     3
2.6     2
Name: count, dtype: int64

In [20]:
# check if rate for two is consistently formatted
df['Rate for two'].unique()

<StringArray>
[  '500',   '600',   '550', '1,200', '1,000',   '800',   '950',   '850',
 '2,000', '1,100',   '900',   '350',   '450',   '700',   '750',   '650',
 '1,500', '1,300',   '300', '1,250', '1,800',   '250',   '400', '1,600',
 '1,400',   '150', '2,300', '1,700']
Length: 28, dtype: str

In [22]:
# inspect if rate for two contains unexpected characters
df['Rate for two'].astype(str).str.extract(r'([^\d\s])')[0].value_counts(dropna=False)

0
NaN    573
,      202
Name: count, dtype: int64

In [23]:
# check whether non-empty values consist only of digits
df['Rate for two'].astype(str).str.strip().str.fullmatch(r'\d+').value_counts()

Rate for two
True     573
False    202
Name: count, dtype: int64

In [24]:
# check how many unique restaurants
df['Name'].nunique()

299

In [25]:
# check how many reviews each resto has
df['Name'].value_counts()

Name
The Chocolate Room                                    11
Oven The Bakery & Cafe                                 6
McCafe by McDonald's                                   6
Blue Tokai Coffee Roasters                             6
Express Cafe                                           6
Brown Sugar                                            6
Cafe Coffee Day                                        6
The Ritz-Carlton Tea Lounge: The Ritz-Carlton          5
Tanoshii Cafe                                          5
One World - The Coffee Studio                          5
Aeka Coffee                                            5
Kana By Coffee Mechanics                               5
The Farmhouse Kitchen & Bakery                         5
The 2.0 Drinks                                         5
Crackers Cafe                                          5
Funkys Cafe                                            5
Django                                                 5
The Creamery Cafe                                      5
Seven Lakes Cafe And Restaurant                        5
Kaleidoscope                                           5
Zolocrust - Hotel Clarks Amer                          5
Alora Cafe & Patisserie                                5
Coffee Network                                         5
The Ground Baking Co.                                  5
Wanna Puff                                             5
Esperance                                              5
The Food Garden                                        5
Xero Degrees                                           4
I Love Sandwich House                                  4
Cafe Catchers                                          4
Creamoholic Cafe                                       4
Ventana                                                4
Jamie's Pizzeria By Jamie Oliver                       4
De Baillio                                             4
Cafe Cremyday                                          4
Banoffee                                               4
Kargeens                                               4
Pot Head                                               4
Barista Coffee                                         4
Cafe Down The Alley                                    4
Clean Slate Cafe                                       4
Writer's Cafe                                          4
World Brew Cafe                                        4
Narcos Cafe                                            4
Cosmo Bar & Bistro                                     4
Roastery Coffee House                                  4
Jashn                                                  4
Starstud Cafe                                          4
Half Brew                                              4
Viona Baristro                                         4
Cafe Two Pi R                                          4
Royal Bakery Cafeteria                                 4
The Pod Cafe                                           4
Movenpick Ice Cream Boutique                           4
Chamiers Cafe                                          4
Scooby's Cafe                                          4
The FreshlyMade                                        4
The Big Bro                                            4
Celeste Cafe & Bar                                     4
Pokket Cafe                                            4
Kaffee - Mast Hai                                      3
Indie Brewed Cafe                                      3
Brewer Cafe & Restro                                   3
Vince Cafe                                             3
Cafe Selfie                                            3
58 Cafe House                                          3
Cafe Cos                                               3
Shiva's Coffee Bar                                     3
Food Costa                                             3
Tony Cafe                                              3
Veronica's                                             3
Pune Baking Company - JW Marriott Pune                 3
Le Coffee House                                        3
Le Flamington                                          3
Back To Basics                                         3
The Burger Barn Cafe                                   3
La Segreto Cafe And Resto                              3
Ambrosia Patisserie & Cafe - Ambrosia Resort & Spa     3
Cocoa Patisserie and Bakery                            3
Cafe From The Tree                                     3
Journey                                                3
BICE - The Cake Shop & Cafe                            3
Cafe Milano                                            3
Cafe Gupshup                                           3
Cafe Canephora                                         3
Café De Conta                                          3
Reminisce Cafe                                         3
Tea Trails Cafe                                        3
GoodFellas Cafe                                        3
Conçu                                                  3
Tutto Bene - Desserts Cafe by Little Italy             3
Ciciana                                                3
The Pet People Cafe                                    3
Haru Asian Bistro                                      3
Qmin                                                   3
The Grey House Cafe                                    3
Burp                                                   3
The Old Madras Baking Company                          3
Cafe OTW - On The Way                                  3
Indian Paratha Company                                 3
Chill-Um Cafe                                          3
Charlie Chaplin Lavegano                               3
Start Your Day Cafe                                    3
Bistro 1427                                            3
Tea Time                                               3
Cafe Centralis                                         3
Yummy Yoga                                             3
Gulaabo - The Customized Cafe                          3
Cafe Cook Hook                                         3
Z27 By Cafe Lake City                                  3
The Tick Tock Cafe & Restaurant                        3
Terra Gourmet                                          3
Chum-Bakk Cafe                                         3
Qissa Cafe                                             3
Assamica                                               3
Cafe Cornerstone By Pallavi Daga                       3
Just Coffee Place                                      3
Phele Chai                                             3
The Over Halt In                                       3
House Of Beans                                         3
DM Techno Cafe                                         3
Lloyd's House                                          3
Crush On Coffee                                        3
Sujangarh Cafe                                         3
Brewing Brokers Cafe                                   3
The Waves Cafe                                         3
Red Flames Pizzaria                                    3
Fantasy Bakery And Cafe                                3
Aieroc Resto Cafe                                      3
The Market - Fairfield by Marriott                     3
Your Own Brew Cafe                                     3
Crumb's Patisserie And Cafe                            3
The AMP Cafe & Eatery                                  3
Destiny Cafe And Restaurant                            3
The Board Room                                         3
Tryst Cafe                                             3
League of Breaks Cafe                                  3
Art Cafe                                               3
Cafe Blanca                                            3
Cafe Adoniya                                           3
Pannacottas                                            3
The Hedgehog Café                                      3
BenJi Cafe                                             3
The Inside Cafe                                        3
Oliver Brown                                           2
The Mohalla                                            2
The Shaka Cafe                                         2
Caffix - The Tech Cafe                                 2
Gamysticafe                                            2
Core The Coffee Shop @ Lithosphere                     2
Silver Fork Cafe & Restaurant                          2
Lil' Heaven Cafe                                       2
Wagh Bakri Tea Lounge                                  2
Sphere Lounge - Hotel Ramada                           2
Chai Hai Na                                            2
Drunch                                                 2
Cafe After Hours                                       2
Edr Cafe                                               2
The Avenue Cafe                                        2
Ares Cafe                                              2
One O Eight Cafe                                       2
Cafe Nadora By Sneha                                   2
Cafe Peter                                             2
Hustle Snooker Cafe Bistro                             2
Brooster Coffeespot                                    2
Ambrozia Cafe And Patisserie                           2
Cafe Fairytale                                         2
Salisbury Swiss Cafe                                   2
Kallyfso Cafe                                          2
Chai Coffee Charcha                                    2
Gold Rush Cafe                                         2
Cream And Crush                                        2
Aptez Dosa Cafe                                        2
Impresso Espresso Coffee                               2
Monk & Mongoose Cafe                                   2
Cafe Imbibe                                            2
Maverick & Farmer Coffee                               2
Vedic Chai                                             2
Casa Fresco By Tea Brew                                2
The Coffee Brewery                                     2
Secret Spot Cafe                                       2
Fresh Pressery Cafe                                    2
Green Bean Coffee                                      2
Moto Store & Café                                      2
Qube Cafe                                              2
Stava Bistro                                           2
Caffe Pascucci                                         2
Cafe Pink Pajamas                                      2
Belur Cafe                                             2
Shatranj Cafe And Lounge                               2
Cafe Vishala                                           2
Off White                                              2
Step 51 Rooftop Cafe                                   2
The Waffle Co.                                         2
Bombaye House                                          2
The Messy Door Cafe                                    2
Aakraa House                                           2
Coffee Sutra                                           2
Quyu's Cafe                                            2
The-Gorma                                              2
Coffee. Connect                                        2
Chska                                                  2
MD Khane Wala                                          2
Cafe Diona                                             2
Loca By La Multigrain                                  2
The Taapu                                              2
Malgudi Cafe                                           2
Legacy Terrace Cafe And Kitchen                        2
TRCH-Luxury Restro & Lounge                            2
Cafe Kampus                                            2
SST Cakes & Bakes                                      2
The Full Moon Cafe And Restaurant                      2
Merlin Cafe                                            2
Roadies Koffeehouz                                     2
395 - The Modern Cuisine                               2
Koselig                                                2
The Good Stuff                                         2
Alba Bistro                                            2
Mitti - Organic Fresh Desi                             2
Cafe De Casa                                           2
The Nest                                               2
Sassy House - All Day Cafe                             2
Convo@C20                                              2
Nicky's Cafe & Fine Pastries                           2
IL Forno Magico                                        2
Big Jerks                                              2
TCB Cafe                                               2
Mansar Coffee                                          2
Owling By Fat Dad                                      2
Downtown Cafe & Bakery                                 2
French Press Cafe                                      2
BitesBee                                               2
Sardar-Ji-Bakhsh Coffee & Co.                          2
Crush Coffee                                           1
Hobnob Bistro                                          1
Mleko                                                  1
Unlocked                                               1
Novelchef Cafe & Lounge                                1
Cuppuccino                                             1
Fyro                                                   1
Big Blue Bistro                                        1
Rasa Restro Cafe                                       1
Aarambh Cafe                                           1
Smash Cafe                                             1
Brewers - The Coffee Bar                               1
Shambhu's Coffee Bar                                   1
Busy Beans                                             1
Shambhus Cafe                                          1
Cafe Kyzo                                              1
IKOV Art Cafe Studio                                   1
K.K's Cafe                                             1
Cafe Da Al Forno                                       1
Daily Treats - The Westin Pune                         1
BREWBURG                                               1
Words & Sips Book Cafe                                 1
Crazy Cheesy Cafe                                      1
Cafe Time Out                                          1
Coffee Saaz                                            1
Mitico Coffee Roasters                                 1
Cafe Azzure                                            1
SLAY Coffee Bar                                        1
Cool Street                                            1
HumbleBean Coffee                                      1
The Coffee House                                       1
TROT - The Republic Of Taste                           1
Cafe Cosy                                              1
The Café By Foodhall                                   1
Coffea                                                 1
Cafe Indulge                                           1
Cafe +                                                 1
Isobel                                                 1
Caffeinate And Chill                                   1
Green Grotto Bistro                                    1
Camiano Patisserie & Brasserie                         1
Bellissimo Home Cafe                                   1
Uphoria- Cafe & Restro                                 1
Sweet Dough By Kanha                                   1
Team 11 Sports Cafe                                    1
Coffee King Cafe & Restaurant                          1
Richie Rich - On Wheels                                1
Moonstruck Coffee                                      1
Koffee King                                            1
CBI - Coffee Bureau Of Indore                          1
Cafe El Carpediem                                      1
Crazy Coffee                                           1
Amelie's                                               1
The Summer House Eatery                                1
Seeds Lifestyle                                        1
Double Roti                                            1
Sandy's Chocolate Laboratory                           1
Beachville Coffee Roasters                             1
Barrocco                                               1
Cafe CakeBee                                           1
Atte - Glocal Cafe                                     1
Antari By Soul Garden Bistro                           1
Brooklyn Central                                       1
Los Amigo's Cafe                                       1
Brookies                                               1
Pistol 06 Cafe And Lounge                              1
Name: count, dtype: int64

In [26]:
# check how many unique cities
df['City'].nunique()

10

In [27]:
# check number of reviews per city
df['City'].value_counts()

City
bangalore     166
jaipur        142
pune          135
ahmedabad     100
chennai        65
chandigarh     57
indore         52
udaipur        31
surat          24
mumbai          3
Name: count, dtype: int64

In [28]:
# check distribution of reviews across restaurants
review_distribution = df['Name'].value_counts()
review_distribution

Name
The Chocolate Room                                    11
Oven The Bakery & Cafe                                 6
McCafe by McDonald's                                   6
Blue Tokai Coffee Roasters                             6
Express Cafe                                           6
Brown Sugar                                            6
Cafe Coffee Day                                        6
The Ritz-Carlton Tea Lounge: The Ritz-Carlton          5
Tanoshii Cafe                                          5
One World - The Coffee Studio                          5
Aeka Coffee                                            5
Kana By Coffee Mechanics                               5
The Farmhouse Kitchen & Bakery                         5
The 2.0 Drinks                                         5
Crackers Cafe                                          5
Funkys Cafe                                            5
Django                                                 5
The Creamery Cafe                                      5
Seven Lakes Cafe And Restaurant                        5
Kaleidoscope                                           5
Zolocrust - Hotel Clarks Amer                          5
Alora Cafe & Patisserie                                5
Coffee Network                                         5
The Ground Baking Co.                                  5
Wanna Puff                                             5
Esperance                                              5
The Food Garden                                        5
Xero Degrees                                           4
I Love Sandwich House                                  4
Cafe Catchers                                          4
Creamoholic Cafe                                       4
Ventana                                                4
Jamie's Pizzeria By Jamie Oliver                       4
De Baillio                                             4
Cafe Cremyday                                          4
Banoffee                                               4
Kargeens                                               4
Pot Head                                               4
Barista Coffee                                         4
Cafe Down The Alley                                    4
Clean Slate Cafe                                       4
Writer's Cafe                                          4
World Brew Cafe                                        4
Narcos Cafe                                            4
Cosmo Bar & Bistro                                     4
Roastery Coffee House                                  4
Jashn                                                  4
Starstud Cafe                                          4
Half Brew                                              4
Viona Baristro                                         4
Cafe Two Pi R                                          4
Royal Bakery Cafeteria                                 4
The Pod Cafe                                           4
Movenpick Ice Cream Boutique                           4
Chamiers Cafe                                          4
Scooby's Cafe                                          4
The FreshlyMade                                        4
The Big Bro                                            4
Celeste Cafe & Bar                                     4
Pokket Cafe                                            4
Kaffee - Mast Hai                                      3
Indie Brewed Cafe                                      3
Brewer Cafe & Restro                                   3
Vince Cafe                                             3
Cafe Selfie                                            3
58 Cafe House                                          3
Cafe Cos                                               3
Shiva's Coffee Bar                                     3
Food Costa                                             3
Tony Cafe                                              3
Veronica's                                             3
Pune Baking Company - JW Marriott Pune                 3
Le Coffee House                                        3
Le Flamington                                          3
Back To Basics                                         3
The Burger Barn Cafe                                   3
La Segreto Cafe And Resto                              3
Ambrosia Patisserie & Cafe - Ambrosia Resort & Spa     3
Cocoa Patisserie and Bakery                            3
Cafe From The Tree                                     3
Journey                                                3
BICE - The Cake Shop & Cafe                            3
Cafe Milano                                            3
Cafe Gupshup                                           3
Cafe Canephora                                         3
Café De Conta                                          3
Reminisce Cafe                                         3
Tea Trails Cafe                                        3
GoodFellas Cafe                                        3
Conçu                                                  3
Tutto Bene - Desserts Cafe by Little Italy             3
Ciciana                                                3
The Pet People Cafe                                    3
Haru Asian Bistro                                      3
Qmin                                                   3
The Grey House Cafe                                    3
Burp                                                   3
The Old Madras Baking Company                          3
Cafe OTW - On The Way                                  3
Indian Paratha Company                                 3
Chill-Um Cafe                                          3
Charlie Chaplin Lavegano                               3
Start Your Day Cafe                                    3
Bistro 1427                                            3
Tea Time                                               3
Cafe Centralis                                         3
Yummy Yoga                                             3
Gulaabo - The Customized Cafe                          3
Cafe Cook Hook                                         3
Z27 By Cafe Lake City                                  3
The Tick Tock Cafe & Restaurant                        3
Terra Gourmet                                          3
Chum-Bakk Cafe                                         3
Qissa Cafe                                             3
Assamica                                               3
Cafe Cornerstone By Pallavi Daga                       3
Just Coffee Place                                      3
Phele Chai                                             3
The Over Halt In                                       3
House Of Beans                                         3
DM Techno Cafe                                         3
Lloyd's House                                          3
Crush On Coffee                                        3
Sujangarh Cafe                                         3
Brewing Brokers Cafe                                   3
The Waves Cafe                                         3
Red Flames Pizzaria                                    3
Fantasy Bakery And Cafe                                3
Aieroc Resto Cafe                                      3
The Market - Fairfield by Marriott                     3
Your Own Brew Cafe                                     3
Crumb's Patisserie And Cafe                            3
The AMP Cafe & Eatery                                  3
Destiny Cafe And Restaurant                            3
The Board Room                                         3
Tryst Cafe                                             3
League of Breaks Cafe                                  3
Art Cafe                                               3
Cafe Blanca                                            3
Cafe Adoniya                                           3
Pannacottas                                            3
The Hedgehog Café                                      3
BenJi Cafe                                             3
The Inside Cafe                                        3
Oliver Brown                                           2
The Mohalla                                            2
The Shaka Cafe                                         2
Caffix - The Tech Cafe                                 2
Gamysticafe                                            2
Core The Coffee Shop @ Lithosphere                     2
Silver Fork Cafe & Restaurant                          2
Lil' Heaven Cafe                                       2
Wagh Bakri Tea Lounge                                  2
Sphere Lounge - Hotel Ramada                           2
Chai Hai Na                                            2
Drunch                                                 2
Cafe After Hours                                       2
Edr Cafe                                               2
The Avenue Cafe                                        2
Ares Cafe                                              2
One O Eight Cafe                                       2
Cafe Nadora By Sneha                                   2
Cafe Peter                                             2
Hustle Snooker Cafe Bistro                             2
Brooster Coffeespot                                    2
Ambrozia Cafe And Patisserie                           2
Cafe Fairytale                                         2
Salisbury Swiss Cafe                                   2
Kallyfso Cafe                                          2
Chai Coffee Charcha                                    2
Gold Rush Cafe                                         2
Cream And Crush                                        2
Aptez Dosa Cafe                                        2
Impresso Espresso Coffee                               2
Monk & Mongoose Cafe                                   2
Cafe Imbibe                                            2
Maverick & Farmer Coffee                               2
Vedic Chai                                             2
Casa Fresco By Tea Brew                                2
The Coffee Brewery                                     2
Secret Spot Cafe                                       2
Fresh Pressery Cafe                                    2
Green Bean Coffee                                      2
Moto Store & Café                                      2
Qube Cafe                                              2
Stava Bistro                                           2
Caffe Pascucci                                         2
Cafe Pink Pajamas                                      2
Belur Cafe                                             2
Shatranj Cafe And Lounge                               2
Cafe Vishala                                           2
Off White                                              2
Step 51 Rooftop Cafe                                   2
The Waffle Co.                                         2
Bombaye House                                          2
The Messy Door Cafe                                    2
Aakraa House                                           2
Coffee Sutra                                           2
Quyu's Cafe                                            2
The-Gorma                                              2
Coffee. Connect                                        2
Chska                                                  2
MD Khane Wala                                          2
Cafe Diona                                             2
Loca By La Multigrain                                  2
The Taapu                                              2
Malgudi Cafe                                           2
Legacy Terrace Cafe And Kitchen                        2
TRCH-Luxury Restro & Lounge                            2
Cafe Kampus                                            2
SST Cakes & Bakes                                      2
The Full Moon Cafe And Restaurant                      2
Merlin Cafe                                            2
Roadies Koffeehouz                                     2
395 - The Modern Cuisine                               2
Koselig                                                2
The Good Stuff                                         2
Alba Bistro                                            2
Mitti - Organic Fresh Desi                             2
Cafe De Casa                                           2
The Nest                                               2
Sassy House - All Day Cafe                             2
Convo@C20                                              2
Nicky's Cafe & Fine Pastries                           2
IL Forno Magico                                        2
Big Jerks                                              2
TCB Cafe                                               2
Mansar Coffee                                          2
Owling By Fat Dad                                      2
Downtown Cafe & Bakery                                 2
French Press Cafe                                      2
BitesBee                                               2
Sardar-Ji-Bakhsh Coffee & Co.                          2
Crush Coffee                                           1
Hobnob Bistro                                          1
Mleko                                                  1
Unlocked                                               1
Novelchef Cafe & Lounge                                1
Cuppuccino                                             1
Fyro                                                   1
Big Blue Bistro                                        1
Rasa Restro Cafe                                       1
Aarambh Cafe                                           1
Smash Cafe                                             1
Brewers - The Coffee Bar                               1
Shambhu's Coffee Bar                                   1
Busy Beans                                             1
Shambhus Cafe                                          1
Cafe Kyzo                                              1
IKOV Art Cafe Studio                                   1
K.K's Cafe                                             1
Cafe Da Al Forno                                       1
Daily Treats - The Westin Pune                         1
BREWBURG                                               1
Words & Sips Book Cafe                                 1
Crazy Cheesy Cafe                                      1
Cafe Time Out                                          1
Coffee Saaz                                            1
Mitico Coffee Roasters                                 1
Cafe Azzure                                            1
SLAY Coffee Bar                                        1
Cool Street                                            1
HumbleBean Coffee                                      1
The Coffee House                                       1
TROT - The Republic Of Taste                           1
Cafe Cosy                                              1
The Café By Foodhall                                   1
Coffea                                                 1
Cafe Indulge                                           1
Cafe +                                                 1
Isobel                                                 1
Caffeinate And Chill                                   1
Green Grotto Bistro                                    1
Camiano Patisserie & Brasserie                         1
Bellissimo Home Cafe                                   1
Uphoria- Cafe & Restro                                 1
Sweet Dough By Kanha                                   1
Team 11 Sports Cafe                                    1
Coffee King Cafe & Restaurant                          1
Richie Rich - On Wheels                                1
Moonstruck Coffee                                      1
Koffee King                                            1
CBI - Coffee Bureau Of Indore                          1
Cafe El Carpediem                                      1
Crazy Coffee                                           1
Amelie's                                               1
The Summer House Eatery                                1
Seeds Lifestyle                                        1
Double Roti                                            1
Sandy's Chocolate Laboratory                           1
Beachville Coffee Roasters                             1
Barrocco                                               1
Cafe CakeBee                                           1
Atte - Glocal Cafe                                     1
Antari By Soul Garden Bistro                           1
Brooklyn Central                                       1
Los Amigo's Cafe                                       1
Brookies                                               1
Pistol 06 Cafe And Lounge                              1
Name: count, dtype: int64

In [32]:
# descriptive stats for review distribution
review_distribution.describe().T.round(2)

count    299.00
mean       2.59
std        1.34
min        1.00
25%        2.00
50%        2.00
75%        3.00
max       11.00
Name: count, dtype: float64